# Build for XamAR.Forms and XamAR.Native
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

name: $(majorMinorVersion).$(semanticVersion) # $(rev:r) # NOTE: rev resets when the default retention period expires

# pipeline variables
variables:
  majorMinorVersion: 0.2
  # semanticVersion counter is automatically incremented by one in each execution of pipeline
  # second parameter is seed value to reset to every time the referenced majorMinorVersion is changed
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]
  projectName: 'XamAR'
  buildConfiguration: 'Release'

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
# To manually select a Xamarin SDK version on the Microsoft-hosted macOS agent,
# configure this task with the *Mono* version that is associated with the
# Xamarin SDK version that you need, and set the "enabled" property to true.
# See https://go.microsoft.com/fwlink/?linkid=871629
#- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
#  displayName: 'Select the Xamarin SDK version'
#  enabled: false

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '5c9d08c5-50c9-457d-84f9-f2402394e095'

- task: DotNetCoreCLI@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'
    projects: |
      **/XamAR.Forms.csproj
      **/XamAR.Native.csproj

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/XamAR.Forms.csproj;**/XamAR.Native.csproj'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'push'
#    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
#    nuGetFeedType: 'internal'
#    publishVstsFeed: '5c9d08c5-50c9-457d-84f9-f2402394e095'
